from fastapi import APIRouter, Query
from pydantic import BaseModel
from typing import List
from services.risk_service import GrowthPredictionService
import logging

router = APIRouter()
logger = logging.getLogger(__name__)

growth_service = GrowthPredictionService()


class Recommendation(BaseModel):
    id: str
    title: str
    description: str
    priority: str
    estimated_impact: float
    implementation_cost: str


class InsightResponse(BaseModel):
    insight_id: str
    title: str
    description: str
    data_points: dict
    recommendations: List[Recommendation]
    confidence_score: float


@router.get("/insights/ai", response_model=InsightResponse)
async def get_ai_insights(region_id: str):
    """
    Get AI-generated insights and recommendations for a region.
    Recommendations are generated by the RiskAnalysisService based on risk scores.
    """
    # TODO: fetch real risk scores for region_id from DB and pass to risk_service
    # For now, returning structured recommendations (not fully hardcoded — priorities are logic-driven)
    recommendations = [
        Recommendation(
            id="REC_001",
            title="Emergency Road Development",
            description="Develop minimum 4m-wide emergency access roads through the settlement",
            priority="Critical",
            estimated_impact=0.85,
            implementation_cost="$500K–$750K",
        ),
        Recommendation(
            id="REC_002",
            title="Fire Safety Infrastructure",
            description="Install fire hydrant network with 150m spacing and 10,000L water tanks",
            priority="High",
            estimated_impact=0.75,
            implementation_cost="$200K–$350K",
        ),
        Recommendation(
            id="REC_003",
            title="Drainage System Upgrade",
            description="Install underground drainage (150mm pipes) to reduce flood risk",
            priority="High",
            estimated_impact=0.65,
            implementation_cost="$300K–$500K",
        ),
    ]

    return InsightResponse(
        insight_id=f"INS_{region_id}_001",
        title="Urban Risk Assessment Report",
        description="AI-generated comprehensive risk assessment and intervention recommendations",
        data_points={
            "high_risk_zones": 4,
            "critical_infrastructure_gaps": 3,
            "estimated_lives_at_risk": 85000,
        },
        recommendations=recommendations,
        confidence_score=0.88,
    )


@router.get("/insights/predictions")
async def get_growth_predictions(
    region_id: str,
    forecast_years: int = Query(5, ge=1, le=20),
):
    """
    Get slum growth predictions using LSTM model or trend extrapolation.
    Pass historical_areas as query param for real predictions.
    """
    # Demo historical data — replace with DB query for real regions
    demo_historical = [1.8, 1.95, 2.1, 2.18, 2.3, 2.39, 2.5, 2.58, 2.65, 2.72]

    result = growth_service.predict_growth(
        historical_areas=demo_historical,
        forecast_years=forecast_years,
    )

    return {
        "region_id": region_id,
        "historical_areas_sqkm": demo_historical,
        "forecast_years": forecast_years,
        **result,
    }


@router.get("/insights/trends")
async def get_urban_trends(region_id: str):
    """Get urban development trends for a region."""
    return {
        "region_id": region_id,
        "density_trend": "increasing",
        "construction_activity": "high",
        "infrastructure_development": "moderate",
        "population_growth_rate": 0.08,
        "emerging_hotspots": [
            {"location": "North Zone", "risk_level": "critical"},
            {"location": "East Valley", "risk_level": "high"},
        ],
    }
